name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Test Part1
      run: ./part1.rb

    - name: Test Part2
      run: ./part2.rb